name: Sumo1v1
api: 3.14.0
version: 1.0.6
main: davidflash\sumo1v1\OneVsOne
author: DavidFlash
description: sumo minigame plugin
website: https://github.com/DavidFlashCZ/Sumo1v1

permissions:
  1vs1.cmd:
    description: Permission to all Sumo commands
    default: op
    children:
      1vs1.cmd.help:
        description: Permission for /sumo help
        default: op
      1vs1.cmd.create:
        description: Permission for /sumo create
        default: op
      1vs1.cmd.remove:
        description: Permission for /sumo remove
        default: op
      1vs1.cmd.set:
        description: Permission for /sumo set
        default: op
      1vs1.cmd.arenas:
        description: Permission for /sumo arenas
        default: op
      1vs1.cmd.join:
        description: Permission for /sumo join
        default: true